[settings]
idiomatic_version_file_enable_tools = ["node"]

[tools]
python = { version = "3.14.6", install_env = { CONFIGURE_OPTS = "--enable-optimizations" } }
uv = "latest"

[env]
UV_PYTHON = { value = "{{ tools.python.path }}", tools = true }
