#!/usr/bin/env python3
"""Host-side A/B of the DAC-path video *tempo* clock: petscii vs mhires.

The mhires_dac_tempo_stretch memory reports that a video forced onto the 4-bit
$D418 DAC (``[audio].backend = "dac"``) plays perceptibly SLOW — but at correct
PITCH — when the display is a bitmap mode (mhires/hires); in char (petscii) mode
the same clip is fine. The video is slaved to the audio *position* clock
(``AudioStreamer.position_seconds()``), which on the host-DMA DAC path is
DRAIN-based: (samples pushed − samples still queued) / sample_rate. If the audio
worker's drain to the C64 ring stalls (mutex contention with the big bitmap
host-DMA push), that clock advances slower than real time and the whole timeline
stretches.

This probe measures that directly and cheaply — NO Cam Link capture, NO rapid
U64 REST polling (both of which the memories warn against). It just runs
``python -m c64cast`` in each display mode with ``-vv`` and reads the app's own
telemetry from the log:

  * ``clock/wall``  — master-clock speed vs real time (the tempo-stretch metric;
                      <1.0 = slow). Added to VideoScene's A/V-lag telemetry.
  * underruns       — full/partial (padding = an *audio* tempo stretch signature)
  * host-DMA servo gap last/min/max

Because it's the app's own host-side clock (referenced to time.monotonic), it is
immune to the uniform ~9.6% Cam Link capture-path rate offset
(avfoundation_capture_drops_samples) — that offset only lives in the capture, not
in c64cast's own numbers.

    scripts/diags/mhires_tempo_clock_ab.py
    scripts/diags/mhires_tempo_clock_ab.py --clip assets/videos/Wham*.mp4 --seconds 40
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
import time
from pathlib import Path

import _diaglib as d

DEFAULT_CLIP = "assets/videos/Wham! - Wake Me Up Before You Go-Go (Official Video).mp4"

CLOCK_RE = re.compile(r"clock/wall=([0-9.]+)")
UNDERRUN_RE = re.compile(r"(\d+) full \+ (\d+) partial underruns")
SERVO_RE = re.compile(r"servo gap last=(-?\d+) min=(-?\d+) max=(-?\d+)")
LAG_RE = re.compile(r"A/V lag summary: min=([-+0-9.]+) avg=([-+0-9.]+) max=([-+0-9.]+)")


def _write_config(out: Path, clip: str, label: str, display: str) -> Path:
    abs_clip = str(Path(clip).resolve())
    toml = f"""# generated by mhires_tempo_clock_ab.py — {label}
[audio]
enabled = true
backend = "dac"

[playlist]
loop = false
interleave_videos = false

[[scenes]]
type = "video"
file = "{abs_clip}"
display = "{display}"
"""
    p = out / f"tempo_ab_{label}.toml"
    p.write_text(toml)
    return p


def run_condition(url: str, clip: str, label: str, display: str, secs: float) -> dict:
    out = d.out_dir()
    cfg = _write_config(out, clip, label, display)
    app_log = d.stamped(f"tempo_{label}_app", "log")
    boot_margin = 8.0

    print(f"\n=== {label}: display={display} ===")
    argv = [d.python_exe(), "-m", "c64cast", "--config", str(cfg), "--url", url, "-vv"]
    with open(app_log, "w") as fh:
        app = subprocess.Popen(argv, stdout=fh, stderr=subprocess.STDOUT)
        try:
            time.sleep(secs + boot_margin)
        finally:
            app.terminate()
            try:
                app.wait(timeout=10)
            except subprocess.TimeoutExpired:
                app.kill()
                app.wait(timeout=5)

    text = Path(app_log).read_text()
    clocks = [float(m) for m in CLOCK_RE.findall(text)]
    res: dict = {"label": label, "display": display, "log": str(app_log)}
    res["clock_samples"] = clocks
    res["clock_final"] = clocks[-1] if clocks else None
    # Median of the steady-state (drop the first couple readings = warmup).
    steady = clocks[2:] if len(clocks) > 3 else clocks
    res["clock_median"] = sorted(steady)[len(steady) // 2] if steady else None
    um = UNDERRUN_RE.search(text)
    res["underruns"] = (int(um.group(1)), int(um.group(2))) if um else (0, 0)
    sm = SERVO_RE.search(text)
    res["servo_gap"] = (int(sm.group(1)), int(sm.group(2)), int(sm.group(3))) if sm else None
    lm = LAG_RE.search(text)
    res["av_lag_ms"] = (float(lm.group(1)), float(lm.group(2)), float(lm.group(3))) if lm else None

    print(f"    log: {app_log}")
    print(
        f"    clock/wall  median={res['clock_median']}  final={res['clock_final']}"
        f"  ({len(clocks)} readings)"
    )
    print(f"    underruns   full={res['underruns'][0]} partial={res['underruns'][1]}")
    print(f"    servo gap   {res['servo_gap']}")
    print(f"    A/V lag ms  {res['av_lag_ms']}")
    return res


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument("--clip", default=DEFAULT_CLIP)
    ap.add_argument("--url", default="u64://192.168.2.64")
    ap.add_argument("--seconds", type=float, default=35.0, help="play seconds per mode")
    ap.add_argument(
        "--modes", nargs="+", default=["petscii", "mhires"], help="display modes to A/B"
    )
    ap.add_argument("--no-reset", action="store_true")
    args = ap.parse_args()

    if not Path(args.clip).exists():
        ap.error(f"clip not found: {args.clip}")

    results = []
    try:
        for display in args.modes:
            results.append(run_condition(args.url, args.clip, display, display, args.seconds))
            time.sleep(1.0)
    finally:
        if not args.no_reset:
            code = d.rest_reset(d.U64_URL)
            print(f"\n[reset] {'HTTP ' + str(code) if code else 'FAILED'}")

    print(f"\n{'=' * 66}\nSUMMARY  (clock/wall <1.0 = tempo stretch)\n{'=' * 66}")
    print(f"{'mode':<10} {'clock/wall(med)':<16} {'underruns':<14} {'servo gap(min..max)':<20}")
    for r in results:
        cm = f"{r['clock_median']:.4f}" if r["clock_median"] is not None else "n/a"
        ur = f"{r['underruns'][0]}f/{r['underruns'][1]}p"
        sg = f"{r['servo_gap'][1]}..{r['servo_gap'][2]}" if r["servo_gap"] else "n/a"
        print(f"{r['display']:<10} {cm:<16} {ur:<14} {sg:<20}")

    meds = {r["display"]: r["clock_median"] for r in results if r["clock_median"]}
    if "petscii" in meds and "mhires" in meds:
        rel = meds["mhires"] / meds["petscii"]
        print(f"\nmhires/petscii clock ratio = {rel:.4f}  ({(rel - 1) * 100:+.2f}%)")
        print("  <0 % → mhires master clock runs slower than petscii = the stretch.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
