#!/usr/bin/env python3
"""Resolve the mhires_dac_tempo_stretch mechanism: measure BOTH audio PITCH
(capture, offset-immune) AND the host-side master-clock speed for petscii vs
mhires on the DAC path, in one run.

Pitch ratio vs source == R / sample_rate (what the NMI actually clocks out).
clock/wall (from the app log) == how fast the drain-based position clock (which
paces the video) advances vs real time.

  * If pitch ≈ 1.0 but clock/wall < 1.0  → audio is FINE; the video-master clock
    is the bug (position_seconds under-reports). Fix the clock.
  * If pitch ≈ clock/wall < 1.0          → the NMI consumer R is genuinely slow;
    audio is slow + flat. Fix R / the rate.

Uses Cam Link audio only (no rapid U64 REST polling). Pitch is measured by
log-spectrum cross-correlation vs the clip's own audio (reused from
nmi_pitch_ab), which is immune to the uniform ~9.6% capture-path rate offset.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
import time
from pathlib import Path

import _diaglib as d
from nmi_pitch_ab import CAP_SR, analyze

DEFAULT_CLIP = "assets/videos/Wham! - Wake Me Up Before You Go-Go (Official Video).mp4"
CLOCK_RE = re.compile(r"clock/wall=([0-9.]+)")


def _write_config(out: Path, clip: str, display: str) -> Path:
    abs_clip = str(Path(clip).resolve())
    toml = f"""# generated by mhires_pitch_tempo_ab.py — {display}
[audio]
enabled = true
backend = "dac"

[playlist]
loop = false
interleave_videos = false

[[scenes]]
type = "video"
file = "{abs_clip}"
display = "{display}"
"""
    p = out / f"pt_ab_{display}.toml"
    p.write_text(toml)
    return p


def run(url: str, clip: str, display: str, secs: float, avf: str) -> None:
    out = d.out_dir()
    cfg = _write_config(out, clip, display)
    wav = str(d.stamped(f"pt_{display}", "wav"))
    app_log = d.stamped(f"pt_{display}_app", "log")
    boot_margin = 7.0
    cap_len = secs + boot_margin + 2.0

    print(f"\n===== {display} =====")
    ff = subprocess.Popen(
        ["ffmpeg", "-hide_banner", "-loglevel", "error", "-y",
         "-f", "avfoundation", "-i", avf, "-t", str(cap_len),
         "-ac", "1", "-ar", str(CAP_SR), wav],
    )  # fmt: skip
    time.sleep(1.5)
    argv = [d.python_exe(), "-m", "c64cast", "--config", str(cfg), "--url", url, "-vv"]
    with open(app_log, "w") as fh:
        app = subprocess.Popen(argv, stdout=fh, stderr=subprocess.STDOUT)
        try:
            time.sleep(secs + boot_margin)
        finally:
            app.terminate()
            try:
                app.wait(timeout=10)
            except subprocess.TimeoutExpired:
                app.kill()
                app.wait(timeout=5)
    ff.wait()

    clocks = [float(m) for m in CLOCK_RE.findall(Path(app_log).read_text())]
    steady = clocks[2:] if len(clocks) > 3 else clocks
    cw = sorted(steady)[len(steady) // 2] if steady else None
    print(f"  clock/wall (host) median = {cw}")
    analyze(wav, clip)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--clip", default=DEFAULT_CLIP)
    ap.add_argument("--url", default="u64://192.168.2.64")
    ap.add_argument("--seconds", type=float, default=24.0)
    ap.add_argument("--avf-audio", default=d.CAMLINK_AVF_AUDIO)
    ap.add_argument("--modes", nargs="+", default=["petscii", "mhires"])
    ap.add_argument("--no-reset", action="store_true")
    args = ap.parse_args()

    if not Path(args.clip).exists():
        ap.error(f"clip not found: {args.clip}")
    try:
        for display in args.modes:
            run(args.url, args.clip, display, args.seconds, args.avf_audio)
            time.sleep(1.0)
    finally:
        if not args.no_reset:
            print(f"\n[reset] HTTP {d.rest_reset(d.U64_URL)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
