#!/usr/bin/env python3
"""Hardware A/B sweep of the NMI $D418 DAC-path audio SAMPLE RATE on the U64,
through the FULL video pipeline (real bus-halt tick-loss present). Used to pick
the shipped ``[audio].sample_rate`` default: play the SAME clip at a range of
rates and measure, for each, whether the NMI consumer keeps up.

Why pitch ratio is the overrun detector
---------------------------------------
Video audio on ``[audio].backend = "dac"`` is resampled ONCE to the configured
``sample_rate`` R_cfg, but the NMI consumer rate R_eff is what actually clocks
samples to the DAC. Playback pitch = R_eff / R_cfg. When R_cfg stays under the
NMI handler's cycle budget, R_eff tracks it and the ratio sits at ~1.0. Push
R_cfg past the ~68-cycle handler worst case (≈15 kHz NTSC) and NMIs queue: R_eff
plateaus below R_cfg, so the captured pitch drops BELOW 1.0 by exactly the
overrun fraction. A rate whose ratio departs from 1.0 (beyond the raw bus-halt
floor a clean low rate shows) is overrunning — that is the ceiling in action.

This complements nmi_pitch_ab.py (which sweeps the compensation KNOBS at a fixed
rate); here the knobs are pinned to the shipped resting values (adaptive off,
pitch_mult 1.0) and the RATE is swept.

Pitch measurement is imported from nmi_pitch_ab (log-f spectral cross-correlation
vs the clip's own decoded track — robust to the ~12 % non-uniform avfoundation
capture drops, which corrupt timing but not pitch; see the
avfoundation_capture_drops_samples memory). No REST polling of the C64 during
capture (that can wedge the unit — no_rapid_u64_reads_during_capture memory).

    scripts/diags/nmi_rate_sweep_ab.py                       # default sweep, mhires
    scripts/diags/nmi_rate_sweep_ab.py --rates 11600 13000 13500 --display petscii
    scripts/diags/nmi_rate_sweep_ab.py --seconds 25 --clip assets/videos/dsp_test_music.mp4

Makes sound on the real U64. Resets the machine on exit unless --no-reset.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
import time
from pathlib import Path

import _diaglib as d

# Reuse the validated pitch-analysis pipeline rather than re-deriving it.
from nmi_pitch_ab import CAP_SR, analyze  # noqa: E402

DEFAULT_CLIP = "assets/videos/dsp_test_music.mp4"
DEFAULT_RATES = (11600, 12000, 13000, 13500)


def _write_config(out: Path, clip: str, rate: int, display: str) -> Path:
    """Single-scene DAC-path video TOML at one sample rate, compensation OFF
    (shipped resting knobs) so the captured pitch == the raw R_eff / rate."""
    abs_clip = str(Path(clip).resolve())
    toml = f"""# generated by nmi_rate_sweep_ab.py — {rate} Hz @ {display}
[audio]
enabled = true
backend = "dac"
sample_rate = {rate}
nmi_rate_adaptive = false
pitch_mult_mhires = 1.0
pitch_mult_hires = 1.0

[playlist]
loop = false
interleave_videos = false

[[scenes]]
type = "video"
file = "{abs_clip}"
display = "{display}"
"""
    p = out / f"rate_ab_{rate}_{display}.toml"
    p.write_text(toml)
    return p


def run_rate(url: str, clip: str, rate: int, display: str, secs: float, avf: str) -> None:
    out = d.out_dir()
    cfg = _write_config(out, clip, rate, display)
    wav = str(d.stamped(f"rate_{rate}_{display}", "wav"))
    boot_margin = 6.0
    cap_len = secs + boot_margin + 2.0

    print(f"\n=== {rate} Hz @ {display} (Nyquist ~{rate / 2000:.1f} kHz) ===")
    ff = subprocess.Popen(
        ["ffmpeg", "-hide_banner", "-loglevel", "error", "-y",
         "-f", "avfoundation", "-i", avf, "-t", str(cap_len),
         "-ac", "1", "-ar", str(CAP_SR), wav],
    )  # fmt: skip
    time.sleep(1.5)  # let the avfoundation stream come up before c64cast boots

    app_log = d.stamped(f"rate_{rate}_{display}_app", "log")
    argv = [d.python_exe(), "-m", "c64cast", "--config", str(cfg), "--url", url, "-vv"]
    with open(app_log, "w") as fh:
        app = subprocess.Popen(argv, stdout=fh, stderr=subprocess.STDOUT)
        try:
            time.sleep(secs + boot_margin)
        finally:
            app.terminate()
            try:
                app.wait(timeout=8)
            except subprocess.TimeoutExpired:
                app.kill()
    ff.wait()
    print(f"    app log: {app_log}")
    # Surface underrun telemetry + servo R read if the teardown path logged them.
    try:
        lines = Path(app_log).read_text().splitlines()
        for key in ("underruns", "clean session"):
            hits = [ln for ln in lines if key in ln]
            for ln in hits[-1:]:
                print(f"    [log] {ln.split('] ', 1)[-1]}")
    except OSError:
        pass
    analyze(wav, clip)


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument("--clip", default=DEFAULT_CLIP, help="video clip to play (full-band tonal)")
    ap.add_argument("--url", default="u64://192.168.2.64", help="connection target")
    ap.add_argument(
        "--rates", type=int, nargs="+", default=list(DEFAULT_RATES), help="sample rates (Hz)"
    )
    ap.add_argument("--display", default="mhires", help="display mode (mhires = heaviest bus load)")
    ap.add_argument("--seconds", type=float, default=25.0, help="play seconds per rate")
    ap.add_argument(
        "--avf-audio", default=d.CAMLINK_AVF_AUDIO, help="ffmpeg avfoundation audio input"
    )
    ap.add_argument("--no-reset", action="store_true", help="leave the machine running")
    args = ap.parse_args()

    if not Path(args.clip).exists():
        ap.error(f"clip not found: {args.clip}")

    try:
        for rate in args.rates:
            run_rate(args.url, args.clip, rate, args.display, args.seconds, args.avf_audio)
            time.sleep(0.5)
    finally:
        if not args.no_reset:
            code = d.rest_reset(args.url if args.url.startswith("http") else d.U64_URL)
            print(f"\n[reset] {'HTTP ' + str(code) if code else 'FAILED'}")

    print(
        "\nRead: a rate whose overall pitch ratio sits at the same near-1.0 value as "
        "the lowest rate is keeping up (clean). A ratio that drops progressively BELOW "
        "that as the rate rises is the NMI handler overrunning — R_eff plateaus under "
        "R_cfg. Pick the highest rate that stays on the clean floor, with margin. Ears "
        "decide HF clarity + glitches too."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
